questions:
  age:
    order:
      - "5-14 years"
      - "15-24 years"
      - "25-34 years"
      - "35-44 years"
      - "45-54 years"
      - "55-64 years"
      - "65+ years"
      - "Not answered"
  durationNix:
    order:
      - "less than a month"
      - "1-6 months"
      - "6 months - 1 year"
      - "1-3 years"
      - "3-10 years"
      - "10+ years"
      - "Not answered"
  durationNixOS:
    order:
      - "Less than 6 months"
      - "6 months - 1 year"
      - "1 year - 3 years"
      - "3-6 years"
      - "6-10 years"
      - "10+ years"
      - "Not answered"
  triedStopTrialNix:
    exclude:
      - "SQ006"